# Data Import

In [1]:
import pandas as pd

In [6]:
pfad = r"C:\Users\annic\OneDrive\Dokumente\Master Technischer Umweltschutz\Master Thesis\Emission_Trajectory_Thesis\Data\321-140-17133-26-Bestand.csv"

stock = pd.read_csv(pfad, encoding="latin1", sep=";")
stock

,Berichtsjahr,Segment,Antriebsart,Jahr der Erstzulassung,Anzahl
0,01.01.2017,Minis,Benzin,1990,954
1,01.01.2017,Minis,Benzin,1991,1774
2,01.01.2017,Minis,Benzin,1992,2396
3,01.01.2017,Minis,Benzin,1993,3957
4,01.01.2017,Minis,Benzin,1994,5480
...,...,...,...,...,...
26429,01.01.2026,Sonstige,Erdgas (CNG) (einschl. bivalent),2012,20
26430,01.01.2026,Sonstige,Erdgas (CNG) (einschl. bivalent),2013,22
26431,01.01.2026,Sonstige,Erdgas (CNG) (einschl. bivalent),2014,10
26432,01.01.2026,Sonstige,Erdgas (CNG) (einschl. bivalent),2017,2
26433,01.01.2026,Sonstige,Erdgas (CNG) (einschl. bivalent),2018,1

In [7]:
pfad = r"C:\Users\annic\OneDrive\Dokumente\Master Technischer Umweltschutz\Master Thesis\Emission_Trajectory_Thesis\Data\321-140-17133-26-ABS.csv"

exits = pd.read_csv(pfad, encoding="latin1", sep=";")
exits

,Berichtsjahr,Segment,Antriebsart,Jahr der Erstzulassung,Anzahl
0,2016,Minis,Benzin,1990,202
1,2016,Minis,Benzin,1991,391
2,2016,Minis,Benzin,1992,728
3,2016,Minis,Benzin,1993,1850
4,2016,Minis,Benzin,1994,2626
...,...,...,...,...,...
21214,2025,Sonstige,Erdgas (CNG) (einschl. bivalent),2003,3
21215,2025,Sonstige,Erdgas (CNG) (einschl. bivalent),2007,1
21216,2025,Sonstige,Erdgas (CNG) (einschl. bivalent),2012,9
21217,2025,Sonstige,Erdgas (CNG) (einschl. bivalent),2013,11
21218,2025,Sonstige,Erdgas (CNG) (einschl. bivalent),2014,2

In [8]:
pfad = r"C:\Users\annic\OneDrive\Dokumente\Master Technischer Umweltschutz\Master Thesis\Emission_Trajectory_Thesis\Data\321-140-17133-26-NZL.csv"

entries = pd.read_csv(pfad, encoding="latin1", sep=";")
entries

     Berichtsjahr   Segment                           Antriebsart  Anzahl
0            2016     Minis                                Benzin  230152
1            2016     Minis                                Diesel    3946
2            2016     Minis                         Elektro (BEV)     954
3            2016     Minis                                Hybrid       1
4            2016     Minis  Flüssiggas (LPG) (einschl. bivalent)     749
..            ...       ...                                   ...     ...
784          2025  Sonstige                                Diesel     399
785          2025  Sonstige                         Elektro (BEV)    4258
786          2025  Sonstige                                Hybrid    2816
787          2025  Sonstige                              Sonstige      30
788          2025  Sonstige  Flüssiggas (LPG) (einschl. bivalent)     153

[789 rows x 4 columns]